services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ollama:
    image: alpine/ollama:latest 
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ollama-init:
    image: alpine/ollama:latest 
    container_name: ollama_downloader
    environment:
      - OLLAMA_HOST=http://ollama:11434 
    command: pull qwen3.5:0.8b
    depends_on:
      - ollama

volumes:
  mongo_data:
  ollama_data: